### ISSUE TITLE
ZeroTouch installer hardcoding values

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTAKHub-Installation#82]
ZeroTouch currently has an hard coded IP for NodeRd flows:
![image](https://user-images.githubusercontent.com/60719165/233070194-a5095c52-101e-453a-af90-b9b00faecdee.png)
the original code of the flow
![image](https://user-images.githubusercontent.com/60719165/233071103-2f2e7fa6-4c70-4fb9-9c6b-6e7f1ed1f191.png)

**Comment by HeroesLament** [comment]
Issue fixed by swapping the mistakenly hard-coded (oopsie!) IP with local loopback address 127.0.0.1. This should be a good fix, as it will work for private or direct public IP servers simultaneously with no logic needed.

On a side note though, I'm making a note to investigate making a handler in the Ansible playbook to compare directly assigned IPs to known RFC-1918 prefixes: 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16, as well as RFC-6598 prefix 100.64.0.0/10. Would be a good way of determining certain settings for the web client linking.

Also side note, we really should have a component of ZT which sets up the hostname of the FTS service and subs in the hostname for fixed IP assignments when possible.
